### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by TabPhy** [The-Fireplace-Minecraft-Mods/Raining-Cats-and-Dogs#1]
So whenever I try to craft a spawn egg for example a dog in a Singleplayer world, it works perfectly fine. But when I do the same on a Multiplayer I play on with my friends, my game crashes every time I try to pull out the egg from the Crafting Table. I get this game crash message:
"The game crashed whilst updating screen events
Error: java.lang.ArrayIndexOutOfBoundsException: -1"
If you know a solution to this, please contact me :)

**Comment by The-Fireplace** [comment]
Post a link to the full crash report, pasted on pastebin.com or
paste.ubuntu.com.
